packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@types/node': ^22.15.3
  '@types/react': ^18.3.20
  '@types/react-dom': ^18.3.6
  eslint: ^9.27.0
  next: ^15.3.1
  prettier: ^3.5.3
  react: ^18.3.1
  react-dom: ^18.3.1
  tailwindcss: ^3.4.17
  typescript: ^5.8.3