packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@types/node': ^22.15.3
  '@types/react': ^18.3.20
  '@types/react-dom': ^18.3.6
  "@tailwindcss/postcss": "^4.1.7"
  eslint: ^9.27.0
  next: ^15.3.2
  prettier: ^3.5.3
  react: ^19.1.0
  react-dom: ^19.1.0
  tailwindcss: ^4.1.7
  tailwind-merge: ^3.3.0
  typescript: ^5.8.3