export const NAMES_CHAPTER_2 = [
    "Mordan Ramsey",
    "Shakira",
    "Tam",
    "Gandr",
    "Hot Pink One",
    "Peasant The Bae",
    "Shiori",
    "Nyavella",
    "Nerissa",
    "Bijou",
    "Mococo",
    "Fuwawa",
    "Roa",
    "Pandora",
    "Gonathon",
    "Liz",
    "Elizabeth",
    "Cecilia",
    "Immerkind",
];
