export const CATEGORY_ICON_MAP: Record<string, string> = {
    gura: "node-gura-opt.webp",
    ina: "node-ina-opt.webp",
    kiara: "node-kiara-opt.webp",
    ame: "node-ame-opt.webp",
    calli: "node-calli-opt.webp",
    bae: "node-bae-opt.webp",
    kronii: "node-kronii-opt.webp",
    irys: "node-irys-opt.webp",
    fauna: "node-fauna-opt.webp",
    moom: "node-mumei-opt.webp",
    fuwawa: "node-fuwawa-opt.webp",
    mococo: "node-mococo-opt.webp",
    shiori: "node-shiori-opt.webp",
    nerissa: "node-nerissa-opt.webp",
    bijou: "node-bijou-opt.webp",
    cecilia: "node-cecilia-opt.webp",
    liz: "node-liz-opt.webp",
    raora: "node-raora-opt.webp",
    gigi: "node-gigi-opt.webp",
    all: "node-lore-opt.webp",
    animatics: "cat-animatics-opt.webp",
    highlight: "node-lore-opt.webp",
};
